### ISSUE TITLE
Cranbourne - Geolocation Pins for other areas

### ISSUE THREAD

**Issue by Lockxish** [benkaiser/covid-vic-exposure-map#7]
Hey Ben,

All three of these show near each other in Cranbourne when they're elsewhere

![image](https://user-images.githubusercontent.com/85085615/120126554-fec3d400-c1ff-11eb-8d25-e46dca64310e.png)

![image](https://user-images.githubusercontent.com/85085615/120126557-008d9780-c200-11eb-80a6-8c60d76ea29f.png)

![image](https://user-images.githubusercontent.com/85085615/120126565-04211e80-c200-11eb-9cd4-75ebafb831b9.png)

**Comment by joehealy** [comment]
A few more too:
![Screenshot from 2021-05-31 11-11-27](https://user-images.githubusercontent.com/2563935/120127010-6dedf800-c201-11eb-829f-bdbe9916cf90.png)
![Screenshot from 2021-05-31 11-11-39](https://user-images.githubusercontent.com/2563935/120127016-70e8e880-c201-11eb-8629-bf788b23865b.png)
![Screenshot from 2021-05-31 11-12-25](https://user-images.githubusercontent.com/2563935/120127019-734b4280-c201-11eb-942f-4b848006ba51.png)

**Comment by benkaiser** [comment]
Hey @joehealy I fixed the incorrect Cranbourne ones.

Would you be open to submitting the changes for the other ones?

Just update `overrides.json` with the id of the location (can be found in data.json) and the correct "lat" and "lon" values. Then run `SUBSCRIPTION_KEY=notneeded node scrape.js` to update data.json with the overrides. (you'll also need to run `npm install` to setup the project with the dependencies).

**Comment by spiltcoffee** [comment]
In some of these cases, it looks like you'd just need to rerun the `scrape.js` and fetch the `lat` and `lon` again.

e.g. 184 is correct if you remove the entry from `data.json` and rerun `scrape.js` - I got these correct looking coords as a result:
```
    "lat": -37.68209,
    "lon": 145.0706
```

Is the `_id` unique forever? Perhaps as older exposure sites get removed, other sites end up reusing past ids? Might need a more robust way to check if a site has already been geocoded?

**Comment by benkaiser** [comment]
@spiltcoffee good call, to mitigate for now I might set it to re-geocode every scrape (except for the override ones)

**Comment by benkaiser** [comment]
@spiltcoffee I changed the overrides.js to be address based rather than _id based, and to ensure that we re-fetch lat/lon whenever an address field is changed on the source data (in case an id changes to a completely different location). I then re-verified all the locations pins again.

@joehealy @LachlanDowning are any of the markers you called out still an issue? I'm thinking I'll build a feature into the site to allow people to manually correct locations markers.

**Comment by joehealy** [comment]
Looking at them again, I think the issue is/was the ids were reused. What was (above and incorrectly) DFO Uni Hill is now correctly Short Straw (Mary St and Glenferrie Rd Hawthorn). Similarly with the German Shepherds club on Victoria St (replaced with correct site).

Please ignore my pull request as I think your solution is better.

**Comment by benkaiser** [comment]
Great, thanks for verifying @joehealy

**Comment by spiltcoffee** [comment]
> @spiltcoffee I changed the overrides.js to be address based rather than _id based, and to ensure that we re-fetch lat/lon whenever an address field is changed on the source data (in case an id changes to a completely different location). I then re-verified all the locations pins again.

Yeah, that makes more sense, and keeps the goal (I've inferred from your code) of not spamming Azure services with requests unnecessarily. Nice.

**Comment by benkaiser** [comment]
Yeah that's the goal @spiltcoffee . I do have to pay for those requests, even if it is pennies 😉
